---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

## Under Construction

This is a placeholder document for the work-in-progress 2022 residential assessment model.

To see the 2021 residential assessment model, visit the [2021-assessment-year](https://gitlab.com/ccao-data-science---modeling/models/ccao_res_avm/-/tree/2021-assessment-year) git tag.

## Athena Guide

#### Table Universe

```{r file_dict, message=FALSE, results='asis', echo=FALSE}
library(dplyr)
library(here)
library(readr)
library(stringr)

file_dict <- read_csv(here("R", "file_dict.csv"))
file_dict %>%
  distinct(athena_table, observation_unit, primary_key, description) %>%
  filter(!is.na(athena_table)) %>%
  arrange(athena_table) %>%
  rename_with(~ str_to_title(gsub("_", " ", .x))) %>%
  knitr::kable(format = "markdown")
```

#### Run Outputs

```{r file_dict2, message=FALSE, results='asis', echo=FALSE}
file_dict %>%
  select(athena_table, starts_with("run_type_")) %>%
  distinct(athena_table, .keep_all = TRUE) %>%
  filter(!is.na(athena_table)) %>%
  arrange(athena_table) %>%
  setNames(c("Athena Table", "Limited Run", "Full Run")) %>%
  knitr::kable(format = "markdown")
```

## Feature Guide

```{r feature_guide, message=FALSE, results='asis', echo=FALSE}
library(dplyr)
library(tidyr)
library(yaml)
params <- read_yaml("params.yaml")
ccao::vars_dict %>%
  filter(var_is_predictor & var_name_model != "meta_sale_price") %>%
  inner_join(
    as_tibble(params$model$predictor$all),
    by = c("var_name_model" = "value")
  ) %>%
  group_by(var_name_pretty) %>%
  mutate(row = paste0("X", row_number())) %>%
  distinct(
    `Feature Name` = var_name_pretty,
    Category = var_type,
    Type = var_data_type,
    Notes = var_notes,
    var_value, row
  ) %>%
  mutate(Category = recode(
    Category,
    char = "Characteristic", acs5 = "ACS5", loc = "Location",
    prox = "Proximity", ind = "Indicator", time = "Time",
    meta = "Meta", other = "Other"
  )) %>%
  pivot_wider(
    `Feature Name`:`Notes`,
    names_from = row,
    values_from = var_value
  ) %>%
  unite("Possible Values", starts_with("X"), sep = ", ", na.rm = TRUE) %>%
  mutate(Notes = replace_na(Notes, "")) %>%
  arrange(Category) %>%
  relocate(Notes, .after = everything()) %>%
  knitr::kable(format = "markdown")
```