# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##### Setup ####
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load R libraries
options(tidymodels.dark = TRUE)
library(arrow) 
library(assessr)
library(beepr)
library(ccao)
library(dplyr)
library(here)
library(purrr)
library(recipes)
library(stringr)
library(tictoc)
library(tidymodels)
library(treesnip)
source("R/model_funs.R")
source("R/valuation_funs.R")

# Start full script timer
tictoc::tic(msg = "Full Valuation Complete!")

# Set seed for reproducibility
set.seed(27)




# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##### Valuation ####
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load the final stacked model object from file
sm_final_full_fit <- model_load(here("output", "models", "stacked_model.zip"))

# Get the most recent arms length sale for each property in the training dataset
sales_data <- read_parquet(here("input", "modeldata.parquet")) %>%
  filter(ind_arms_length) %>%
  group_by(meta_pin) %>%
  filter(meta_sale_date == max(meta_sale_date)) %>%
  select(meta_pin, meta_sale_price)

# Load the full set of residential properties that need values, join the most
# recent sale and fill all missing sale prices with 0. This is a workaround 
# to prevent NA sales values from being removed when creating predictions
assmntdata <- read_parquet(here("input", "assmntdata.parquet")) %>%
  left_join(sales_data, by = "meta_pin") %>%
  mutate(meta_sale_price = ifelse(!is.na(meta_sale_price), meta_sale_price, 0))

# Get the subset of PINs that actually can be valued by the model (no missing
# or strange data). Then bind the predicted values generated by the model object
# to those IDs. This step is necessary because PINs that can't be modeled are
# removed via the prepped recipe, but ID columns can't actually be passed
# through the model (else they're included in the design matrix)
assmntdata_preds <- bind_cols(
  bake(sm_final_full_fit$recipes$lgbm, assmntdata, has_role("id")),
  predict(
    object = sm_final_full_fit,
    new_data = assmntdata,
    prepped_recipe = sm_final_full_fit$recipes$lgbm
  )
) %>%
  mutate(
    meta_pin = str_pad(meta_pin, 14, "left", "0"),
    meta_class = str_pad(meta_class, 3, "left", "0"),
    meta_multi_code = as.character(meta_multi_code)
  )

# Join predicted values back onto the assessment data and cleanup
assmntdata <- assmntdata %>%
  left_join(
    assmntdata_preds,
    by = c("meta_pin", "meta_class", "meta_multi_code")
  ) %>%
  mutate(
    meta_nbhd = str_pad(meta_nbhd, 3, "left", "0"),
    meta_sale_price = na_if(meta_sale_price, 0)
  )


test <- postval_model(
  data = assmntdata,
  truth = meta_sale_price, 
  estimate = stack, 
  meta_town_code, meta_nbhd
)

assmntdata2 <- assmntdata %>%
  mutate(town_name = town_convert(meta_town_code)) %>%
  mutate(adjusted = predict(test, ., meta_sale_price, stack)) %>%
  select(
    meta_pin, meta_town_code, meta_nbhd, meta_class, meta_sale_price,
    xgb:adjusted
  ) 

temp <- assmntdata2 %>%
  group_by(town_name, name) %>%
  summarize(
    median_ratio = median(value / meta_sale_price, na.rm = TRUE),
    cod = cod(value / meta_sale_price, na.rm = TRUE)
  )

assmntdata2 %>%
  # filter(meta_town_code %in% c("77", "37", "31", "17")) %>%
  ggplot() +
  geom_boxplot(aes(x = value / meta_sale_price, color = name), alpha = 0.5) +
  facet_wrap(vars(town_name)) +
  xlim(0, 3)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##### Post-Modeling ####
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -




### Step 2 - Adjust townhomes to ensure identical townhomes have same value


### Step 3 - Adjust median ratio of group by neighborhood


### Step 4 - Regressivity adjustment?


### Step 5 - Limit excessive ratios


### Step 6 - Identify historic/affordable housing


# TODO: Fix missing data in predictions and from meta model
# TODO: Adjust multi-property PINS