---
title: "Final Hyperparameters"
format: html
---

```{r}
## Final Hyperparameters
# Custom headers for parameter results table, purely aesthetic
param_headers <- withTags(table(
  class = "display",
  thead(
    tr(
      th("run_id"),
      th("config"),
      th("engine"),
      th("seed"),
      th("objective"),
      th("learning rate"),
      th("val prop"),
      th("val type"),
      th("val metric"),
      th("link max depth"),
      th("max bin"),
      th("stop iter"),
      th("num leaves"),
      th("add linked depth"),
      th("feature fraction"),
      th("min gain to split"),
      th("min data in leaf"),
      th("max cat"),
      th("min data in group"),
      th("cat smooth"),
      th("cat l2"),
      th("lamdal1"),
      th("lamdal2"),
      th("max depth")
    )
  )
))
model_parameter_final <- read_parquet("~/Separate Quarto doc into file per topic #74/reports/Separate Quarto doc into file per topic #74/output/parameter_final/model_parameter_final.parquet")

# Table of all final model hyperparameters that were used
model_parameter_final %>%
  select(-any_of(c("num_iterations"))) %>%
  datatable(
    rownames = FALSE,
    filter = "none",
    selection = "none",
    container = param_headers,
    escape = FALSE,
    options = list(
      scrollX = TRUE,
      paging = FALSE,
      searching = FALSE,
      info = FALSE
    )
  ) %>%
  formatRound(c(6:7), digits = 4)
```


```{r}
## Final Hyperparameters
# Dynamically create header row based on selected column names
create_dynamic_headers <- function(data_frame, start_col, end_col) {
  column_names <- colnames(data_frame)[start_col:end_col]
  header_row <- htmltools::tags$tr(lapply(column_names, htmltools::tags$th))
  colspan_value <- length(column_names)

  htmltools::withTags(table(
    class = "display",
    thead(
      tr(
        th(rowspan = 2, "Total Iterations"),
        th(rowspan = 2, "Best Iteration"),
        th(colspan = colspan_value, "Parameters")
      ),
      header_row
    )
  ))
}

model_parameter_final <- read_parquet("~/Separate Quarto doc into file per topic #74/reports/Separate Quarto doc into file per topic #74/output/parameter_final/model_parameter_final.parquet")

# Table of all final model hyperparameters that were used
param_headers <- create_dynamic_headers(model_parameter_final, 1, 25)

model_parameter_final %>%
  select(1:25) %>% # Selecting columns 1 through 25
  datatable(
    rownames = FALSE,
    filter = "none",
    selection = "none",
    container = param_headers,
    escape = FALSE,
    options = list(
      scrollX = TRUE,
      paging = FALSE,
      searching = FALSE,
      info = FALSE
    )
  ) %>%
  formatRound(1:25, digits = 4)
```

