
```{r}
#| cache: true
#| cache-extra: !expr rlang::hash(params)
#| cache-file-1: !expr rlang::hash_file("_baseline_query_data.R")
#| cache-file-2: !expr rlang::hash_file("_utils.R")
source("_baseline_query_data.R")
```


# Distributions of Features (Categorical)

::: {.panel-tabset}

### Assessment set

```{r feature_dist_assess_cat_transform}
baseline_cat_chars_assess_long <- baseline_assessment_data %>%
  select(all_of(categorical_preds)) %>%
  mutate(across(everything(), as.character)) %>%
  pivot_longer(
    cols = everything(),
    names_to = "predictor",
    values_to = "value"
  )
```

```{r feature_dist_assess_cat_plot}
#| column: screen-inset
#| fig-height: !expr fig_height(baseline_cat_chars_assess_long)

plot_small_multiple_histograms(baseline_cat_chars_assess_long, stat = "count")
```

```{r feature_dist_assess_cat_cleanup}
#| output: false

rm(baseline_cat_chars_assess_long)
gc()
```

### Training set

```{r feature_dist_train_cat_transform}
baseline_cat_chars_train_long <- baseline_training_data %>%
  select(all_of(categorical_preds)) %>%
  mutate(across(everything(), as.character)) %>%
  pivot_longer(
    cols = everything(),
    names_to = "predictor",
    values_to = "value"
  )
```

```{r feature_dist_train_cat_plot}
#| column: screen-inset
#| fig-height: !expr fig_height(baseline_cat_chars_train_long)

plot_small_multiple_histograms(baseline_cat_chars_train_long, stat = "count")
```

```{r feature_dist_train_cat_cleanup}
#| output: false

rm(baseline_cat_chars_train_long)
gc()
```

:::

# Distribution of SHAPs (Categorical)

```{r shap_dist_cat_transform}
baseline_cat_shap_long <- baseline_shaps %>%
  select(meta_pin, meta_card_num, all_of(categorical_preds)) %>%
  pivot_longer(
    cols = all_of(categorical_preds),
    names_to = "predictor",
    values_to = "value"
  ) %>%
  left_join(
    baseline_shaps %>%
      select(meta_pin, meta_card_num, all_of(categorical_shaps)) %>%
      pivot_longer(
        cols = all_of(categorical_shaps),
        names_to = "shap_name",
        values_to = "shap_value"
      ) %>%
      mutate(shap_name = str_replace(shap_name, "_shap$", "")),
    by = c("meta_pin", "meta_card_num", "predictor" = "shap_name")
  )
```

```{r shap_dist_cat_plot}
#| column: screen-inset
#| fig-height: !expr fig_height(baseline_cat_shap_long, ncol = ncol_violin)

plot_small_multiple_violins(
  baseline_cat_shap_long,
  "shap_value",
  y_axis_label = "SHAP Value"
)
```

```{r shap_dist_cat_cleanup}
#| output: false

rm(baseline_cat_shap_long)
gc()
```
