---
title: "Model Time Tracking for `r params$run_id`"
execute:
  echo: false
  warning: false
format:
  html:
    embed-resources: true
    toc: true
    toc_float: true
    fig-align: center
    fontsize: 12pt
editor: source
params:
  run_id: 2023-03-14-clever-damani
  year: '2023'
---

```{r}
library(knitr)
source("Setup File.R")
```


## Model Time Tracking

::: panel-tabset
## Training Data (Seen)

Here, the chart demonstrates if the model's median sale price reflects the time trends for the data it has already seen.

```{r, fig.height=8, fig.width=7, out.width="100%"}
model_fit <- lightsnip::lgbm_load(paths$output$workflow_fit$local)
model_recipe <- readRDS(paths$output$workflow_recipe$local)

training_data_pred <- training_data %>%
  mutate(
    pred_card_initial_fmv = predict(
      model_fit,
      new_data = bake(model_recipe, new_data = ., all_predictors())
    )$.pred
  )

training_data_pred %>%
  filter(
    !sv_is_outlier,
    meta_triad_name == run_triad,
    !ind_pin_is_multicard
  ) %>%
  mutate(
    time_interval = lubridate::interval(
      lubridate::make_date(metadata$input_min_sale_year, 1, 1),
      lubridate::ymd(meta_sale_date)
    ),
    time_sale_month = as.numeric(time_interval %/%
      lubridate::dmonths(1)) + 1
  ) %>%
  group_by(meta_township_name, time_sale_month) %>%
  summarize(
    `Median Prediction` = median(pred_card_initial_fmv),
    `Median Sale Price` = median(meta_sale_price)
  ) %>%
  tidyr::pivot_longer(cols = starts_with("Median")) %>%
  ggplot() +
  geom_line(aes(x = time_sale_month, y = value, color = name)) +
  scale_color_manual(
    name = "",
    values = c(
      "Median Prediction" = "red",
      "Median Sale Price" = "blue"
    )
  ) +
  scale_y_continuous(labels = scales::label_dollar(scale = 1e-3, suffix = "K")) +
  facet_wrap(vars(meta_township_name), scales = "free_y", ncol = 3) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 90, hjust = 1),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )
```

## Test Data (Unseen)

This chart looks at sales slightly in the future to see if the model tracks trends which it has not yet seen. 

```{r, fig.height=8, fig.width=7, out.width="100%"}
test_data <- read_parquet(paths$output$test_card$local)
test_data %>%
  filter(meta_triad_code == run_triad_code) %>%
  mutate(
    time_interval = lubridate::interval(
      lubridate::make_date(metadata$input_min_sale_year, 1, 1),
      lubridate::ymd(meta_sale_date)
    ),
    time_sale_month = as.numeric(time_interval %/% lubridate::dmonths(1)) + 1,
    meta_township_name = ccao::town_convert(meta_township_code)
  ) %>%
  group_by(meta_township_name, time_sale_month) %>%
  summarize(
    `Median Prediction` = median(pred_card_initial_fmv),
    `Median Sale Price` = median(meta_sale_price)
  ) %>%
  tidyr::pivot_longer(cols = starts_with("Median")) %>%
  ggplot() +
  geom_line(aes(x = time_sale_month, y = value, color = name)) +
  scale_color_manual(
    name = "",
    values = c("Median Prediction" = "red", "Median Sale Price" = "blue")
  ) +
  scale_y_continuous(labels = scales::label_dollar(scale = 1e-3, suffix = "K")) +
  facet_wrap(vars(meta_township_name),
    scales = "free_y", ncol = 3
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 90, hjust = 1),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )
```
:::
