---
title: "Model I/O QC - Baseline Continuous Variable Analysis"
subtitle: "Distribution by price (disabled due to performance issues)"
author: "Jean Cochrane"
date: "2025-01-24"
execute:
  echo: false
  warning: false
format:
  html:
    embed-resources: true
    # Use SVG for higher-resolution figures
    fig-format: svg
params:
  assessment_year: "2025"
  baseline_run_id: "2025-01-23-dreamy-ida"
---

```{r}
#| cache: true
#| cache-extra: !expr rlang::hash(params)
#| cache-file-1: !expr rlang::hash_file("_baseline_query_data.R")
#| cache-file-2: !expr rlang::hash_file("_utils.R")
```


```{r _price_distance_setup_script}
source("_baseline_query_data.R")
```

::: {.panel-tabset}

### Assessment set

```{r price_dist_assess_cont_transform}
baseline_cont_price_assess_long <- baseline_assessment_data %>%
  select(pred_card_initial_fmv, all_of(continuous_preds)) %>%
  pivot_longer(
    cols = -pred_card_initial_fmv,
    names_to = "predictor",
    values_to = "value"
  )
```

```{r price_dist_assess_cont_plot}
#| column: screen-inset
#| fig-height: !expr fig_height(baseline_cont_price_assess_long,
#| ncol = ncol_line)

plot_small_multiple_lines(
  baseline_cont_price_assess_long,
  "pred_card_initial_fmv",
  y_axis_label = "FMV"
)
```

```{r price_dist_assess_cont_cleanup}
#| output: false

rm(baseline_cont_price_assess_long)
gc()
```

### Training set

```{r price_dist_train_cont_transform}
baseline_cont_price_train_long <- baseline_training_data %>%
  select(meta_sale_price, all_of(continuous_preds)) %>%
  pivot_longer(
    cols = -meta_sale_price,
    names_to = "predictor",
    values_to = "value"
  )
```

```{r price_dist_train_cont_plot}
#| column: screen-inset
#| fig-height: !expr fig_height(baseline_cont_price_train_long,
#| ncol = ncol_line)

plot_small_multiple_lines(
  baseline_cont_price_train_long,
  "meta_sale_price",
  y_axis_label = "FMV"
)
```

```{r price_dist_train_cont_cleanup}
#| output: false

rm(baseline_cont_price_train_long)
gc()
```

:::
