# Remove intermediate objects generated by model creation
# This is done to recover limited memory resources consumed by large objects
rm_intermediate <- function(x, keep = NULL) {
  env <- ls(envir = .GlobalEnv)
  rm_list <- env[
    str_starts(env, x) & !str_detect(env, "final") & !env %in% keep
  ]
  
  if (length(rm_list) > 0) {
    message(paste(
      "Removing intermediate objects:",
      paste(rm_list, collapse = ", ")
    ))
    rm(list = rm_list, envir = .GlobalEnv); gc()
  }
}


# Get environmental variable else a specified default value
model_get_env <- function(x, default) {
  env <- Sys.getenv(x, unset = NA)
  ifelse(!is.na(env), env, default)
} 


# Remove data from iteration results objects created by tune_grid and tune_bayes
model_axe_tune_data <- function(x) {
  stripped <- x %>% select(-any_of("splits"))
  
  attrs <- attributes(x) %>%
    purrr::list_modify("names" = names(stripped))
  attributes(stripped) <- attrs
  stripped
}


# Strip environments created by quosures from recipes, as well as original lvls 
# column and all data not necessary to use predict()
model_axe_recipe <- function(x) {
  axed <- rapply(x, butcher::butcher, how = "replace") %>%
    purrr::list_modify(orig_lvls = NULL)

  class(axed) <- "recipe"
  
  return(axed)
}


# Return prediction from a model and recipe
model_predict <- function(spec, recipe, data) {
  exp(predict(spec, new_data = bake(recipe, data, all_predictors()))$.pred)
}


# Save finale model object. This is basically a workaround to split the 
# LightGBM fit into a separate file since it REALLY doesn't like being saved
# as a RDS
model_save <- function(model, zipfile) {
  
  file_lgbm <- file.path(tempdir(), "lgbm.model")
  lightgbm::lgb.save(model$fit, file_lgbm)
  model$fit <- NULL
  
  file_meta <- file.path(tempdir(), "meta.model")
  saveRDS(model, file_meta)
  
  zip::zipr(zipfile, files = c(file_meta, file_lgbm))
}


# Load model fits from a zip file and combine into one object
model_load <- function(zipfile) {
  ex_dir <- tempdir()
  zip::unzip(zipfile, exdir = ex_dir)
  
  model <- readRDS(file.path(ex_dir, "meta.model"))
  model$fit <- lightgbm::lgb.load(file.path(ex_dir, "lgbm.model"))
  
  return(model)
}
