---
title: "Model Summary"
author: "Cook County Assessor's Office"
date: "`r format(Sys.time(), '%d %B, %Y @ %r')`"
output: html_document
---

```{r setup, include=FALSE}
library(arrow)
library(dplyr)
library(tidyr)
library(DT)
library(sf)
library(ggplot2)
library(stringr)
library(ccao)
library(assessr)
source("cknn_funs.R")
source("utils.R")

knitr::opts_chunk$set(echo = FALSE)
```

## Overall Results

```{r, message=FALSE}
# Load the test set results from file
test <- read_parquet("../data/testdata.parquet")

# Create a summary of test set results by township
test_summary <- test %>%
  select(meta_town_code, meta_sale_price, ends_with("sale_price")) %>%
  mutate(
    town_name = town_convert(meta_town_code),
    outlier = is_outlier(stack_sale_price / meta_sale_price)
  ) %>%
  rename_with(
    ~ gsub("_sale_price", "", .x),
    meta_sale_price:stack_sale_price
  ) %>%
  group_by(town_name) %>%
  summarize(
    count = n(),
    across(enet:stack, ~ cod(.x / meta), .names = "{.col}_cod"),
    num_trimmed = sum(outlier),
    across(stack, ~ cod((.x / meta)[!outlier]), .names = "{.col}_cod_trim")
  ) %>%
  arrange(stack_cod_trim) %>%
  rename_with(~ gsub("_cod", "", .x), c(ends_with("_cod"), ends_with("_trim")))

# Create an interactive table of the test set results by township
test_summary %>%
  datatable(
    rownames = FALSE,
    filter = "none",
    autoHideNavigation = TRUE,
    selection = "none",
    options = list(
      autoWidth = TRUE,
      paging = FALSE,
      searching = FALSE,
      info = FALSE
    )
  ) %>%
  formatRound(2, digits = 0) %>%
  formatRound(c(3:7, 9))

```

### Map of COD by Township by Model Type

```{r}
# Generate triad-level map of outlier
test_summary %>%
  pivot_longer(c(enet:stack, stack_trim)) %>%
  left_join(ccao::town_shp, by = c("town_name" = "township_name")) %>%
  st_set_geometry("geometry") %>%
  mutate(name = factor(name, levels = model_order)) %>%
ggplot() +
  geom_sf(aes(fill = value, geometry = geometry)) +
  scale_fill_distiller(name = "COD", palette = "Spectral") +
  facet_wrap(vars(name)) +
  theme_void()
```

### Outliers by Triad

```{r, message = FALSE, out.width='100%'}
# Generate township map of each model
test %>%
  select(
    meta_town_code, meta_sale_price, stack_sale_price,
    geo_longitude, geo_latitude
  ) %>%
  mutate(outlier = is_outlier(stack_sale_price / meta_sale_price)) %>%
  filter(outlier) %>%
  st_as_sf(coords = c("geo_longitude", "geo_latitude"), crs = 3435) %>%
ggplot() +
  geom_sf(data = ccao::town_shp, aes(geometry = geometry)) +
  geom_sf() +
  theme_void()
```

## Model Results

---

### Best Parameters

```{r}

# Load individual model results from file
enet_results <- read_parquet("../data/models/enet_results.parquet")
xgb_results <- read_parquet("../data/models/xgb_results.parquet")
rf_results <- read_parquet("../data/models/rf_results.parquet")
cknn_results <- read_parquet("../data/models/cknn_results.parquet") %>%
  mutate(model = "cknn", log_cod = log(cod)) %>%
  filter(cod == min(cod)) %>%
  select(m:l, log_cod, model) 

# Bind results together and print
bind_rows(
  enet_results %>% mutate(model = "enet"),
  xgb_results %>% mutate(model = "xgb"),
  rf_results  %>% mutate(model = "rf")
) %>%
  group_by(model) %>%
  filter(.metric == "codm") %>%
  filter(mean == min(mean)) %>%
  distinct(mean, .keep_all = TRUE) %>%
  select(-.metric, -.estimator, -n, -.config) %>%
  select(model, log_cod = mean, std_err, everything()) %>%
  bind_rows(cknn_results) %>%
  knitr::kable(digits = 4)


```

### ElasticNet Grid Search

```{r, warning=FALSE}
# Load and plot ElasticNet grid search results
enet_results %>%
  ggplot(aes(penalty, mean, color = .metric)) +
    geom_errorbar(
      aes(ymin = mean - std_err, ymax = mean + std_err),
      alpha = 0.5
    ) +
    geom_line(size = 1.5) +
    facet_wrap(vars(.metric), scales = "free", ncol = 1) +
    scale_x_log10() +
    guides(color = guide_legend(title = "Metric")) +
    theme(legend.position = "none") +
    theme_minimal()
```

### CkNN Grid Search

```{r, message = FALSE}
# Load and plot CkNN grid search results
cknn_results <- read_parquet("../data/models/cknn_results.parquet")
cknn_grid_plot(cknn_results, m, k, l, cod) 
```



