on:
  pull_request:
  push:
    branches: [main, master, "*-assessment-year"]

name: pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run pre-commit checks
        uses: ccao-data/actions/pre-commit@main
